
disabled_rules:
    - inclusive_language
    - redundant_string_enum_value
    - shorthand_operator
    - convenience_type

opt_in_rules:
    - attributes
    - closure_body_length
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - conditional_returns_on_newline
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - discouraged_assert
    - discouraged_none_name
    - discouraged_object_literal
    - discouraged_optional_boolean
    - empty_collection_literal
    - empty_count
    - empty_string
    - empty_xctest_method
    - enum_case_associated_values_count
    - explicit_acl
    - explicit_init
    - explicit_top_level_acl
    - fallthrough
    - fatal_error_message
    - file_header
    - file_name
    - file_name_no_space
    - first_where
    - flatmap_over_map_reduce
    - force_unwrapping
    - ibinspectable_in_extension
    - identical_operands
    - implicit_return
    - implicitly_unwrapped_optional
    - last_where
    - legacy_multiple
    - legacy_objc_type
    - literal_expression_end_indentation
    - modifier_order
    - multiline_arguments
    - multiline_arguments_brackets
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - no_extension_access_modifier
    - number_separator
    - operator_usage_whitespace
    - optional_enum_case_matching
    - overridden_super_call
    - prefer_self_in_static_references
    - prefer_self_type_over_type_of_self
    - prefer_zero_over_explicit_init
    - prohibited_interface_builder
    - reduce_into
    - redundant_nil_coalescing
    - single_test_class
    - sorted_first_last
    - sorted_imports
    - static_operator
    - strict_fileprivate
    - switch_case_on_newline
    - test_case_accessibility
    - toggle_bool
    - trailing_closure
    - type_contents_order
    - unneeded_parentheses_in_closure_argument
    - unowned_variable_capture
    - untyped_error_in_catch
    - unused_import
    - vertical_parameter_alignment_on_call
    - vertical_whitespace_opening_braces
    - vertical_whitespace_closing_braces
    - weak_delegate
    - yoda_condition

conditional_returns_on_newline:
    if_only: true

enum_case_associated_values_count:
    warning: 2
    error: 3

force_cast:
    severity: warning

identifier_name:
    min_length:
        warning: 2
        error: 2

closure_end_indentation:
    severity: error

closure_spacing:
    severity: error
    
attributes:
    always_on_same_line: []
    always_on_line_above: ["@objc","@nonobjc","@available"]

collection_alignment:
    severity: error
    
contains_over_filter_count:
    severity: error
    
contains_over_filter_is_empty:
    severity: error
    
contains_over_first_not_nil:
    severity: error
    
contains_over_range_nil_comparison:
    severity: error
    
contains_over_filter_count:
    severity: error
    
cyclomatic_complexity:
    ignores_case_statements: true
        
discouraged_assert:
    severity: error
    
discouraged_none_name:
    severity: error
    
discouraged_object_literal:
    severity: error
    
discouraged_optional_boolean:
    severity: error
    
empty_collection_literal:
    severity: error
    
empty_string:
    severity: error
    
empty_xctest_method:
    severity: error
    
enum_case_associated_values_count:
    warning: 3
    error: 4
    
explicit_init:
    severity: error
    
explicit_acl:
    severity: error
    
explicit_top_level_acl:
    severity: error
    
fallthrough:
    severity: error
    
fatal_error_message:
    severity: error
    
file_header:
    severity: error
    
file_name:
    severity: error
    
file_name_no_space:
    severity: error
        
first_where:
    severity: error
    
flatmap_over_map_reduce:
    severity: error

ibinspectable_in_extension:
    severity: error

identical_operands:
    severity: error

implicit_return:
    severity: error
    
last_where:
    severity: error

legacy_multiple:
    severity: error

legacy_random:
    severity: error

line_length:
    warning: 140
    ignores_comments: true
    
literal_expression_end_indentation:
    severity: error
    
modifier_order:
    severity: error

multiline_arguments:
    severity: error

multiline_arguments_brackets:
    severity: error

multiline_function_chains:
    severity: error
    
multiline_literal_brackets:
    severity: error

multiline_parameters:
    severity: error

nesting:
    type_level: 2
    
no_extension_access_modifier:
    severity: error

number_separator:
    severity: error

operator_usage_whitespace:
    severity: error

optional_enum_case_matching:
    severity: error
    
overridden_super_call:
    severity: error

prefer_self_in_static_references:
    severity: error

reduce_into:
    severity: error
    
redundant_nil_coalescing:
    severity: error

single_test_class:
    severity: error

sorted_first_last:
    severity: error
    
sorted_imports:
    severity: error

static_operator:
    severity: error

strict_fileprivate:
    severity: error
    
switch_case_on_newline:
    severity: error

test_case_accessibility:
    severity: error

toggle_bool:
    severity: error
    
trailing_closure:
    severity: error
    
trailing_whitespace:
    ignores_empty_lines: true
    
type_contents_order:
    severity: error
    order: [
        [SwiftLintFramework.TypeContent.case],
        [SwiftLintFramework.TypeContent.typeAlias, SwiftLintFramework.TypeContent.associatedType],
        [SwiftLintFramework.TypeContent.subtype],
        [SwiftLintFramework.TypeContent.typeProperty],
        [SwiftLintFramework.TypeContent.instanceProperty],
        [SwiftLintFramework.TypeContent.ibInspectable],
        [SwiftLintFramework.TypeContent.ibOutlet],
        [SwiftLintFramework.TypeContent.typeMethod],
        [SwiftLintFramework.TypeContent.initializer],
        [SwiftLintFramework.TypeContent.deinitializer],
        [SwiftLintFramework.TypeContent.ibAction],
        [SwiftLintFramework.TypeContent.otherMethod],
        [SwiftLintFramework.TypeContent.subscript]
        ]

unneeded_parentheses_in_closure_argument:
    severity: error
    
unowned_variable_capture:
    severity: error
    
untyped_error_in_catch:
    severity: warning
    
unused_import:
    severity: error
    
vertical_parameter_alignment_on_call:
    severity: error
    
weak_delegate:
    severity: error
    
yoda_condition:
    severity: error
    
excluded:
    - ${PWD}/Pods

type_name:
    allowed_symbols: "_"
    severity: warning

reporter: "xcode"
